### ISSUE TITLE
What is this project?

### ISSUE THREAD

**Issue by jesperstarkar** [StilSoft/CasparCgLib#1]
Hi.

Can you please share som info/ideas/plans for this library? As the author of https://github.com/superflytv/casparcg-connection, it would be good to know what else is coming and what challenges you aim to solve. Good to be coordinated.

**Comment by StilSoft** [comment]
Hi jesperstarkar,

Thank you for your interest in this project.

This project is a .NET library for communication with capsarcg server and is written in C#. It will support all the new features of casparcg 2.1 including asynchronous commands (thanks to new "REQ" casparcg command). Soon when i commit initial version of this library i will add more information.

**Comment by jesperstarkar** [comment]
The REQ feature is a baby of mine, from the needs of our AMCP library :)

Didn't mean to open an issue, just didn't find any other way to ping you on Github. What have I missed?

**Comment by StilSoft** [comment]
Hi jesperstarkar,

Sorry but i not interpret your question correctly. 
I'm completely open for sharing ideas and informations. 
You can contact me at: aleksandar.angeleski@stilsoft.net
